name: Deploy to Exabytes

on:
  push:
    branches:
      - master  # Atau 'main' tergantung nama branch Anda

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files to Exabytes
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          # Karena akun FTP langsung mengarah ke root web, kita gunakan /
          server-dir: /
